### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by raine** [h3poteto/kube-job#66]
```
% kube-job -v run --config=/Users/raine/.kube/config --template-file=test.yaml  --args="echo fuga" --container="test"
INFO[0000] Using config file: /Users/raine/.kube/config
INFO[0000] Received args:
INFO[0000] echo
INFO[0000] fuga
INFO[0000] Removing the job: job-3d6ccb546fd16bb568c75fa2002f0c8d
FATA[0000] jobs.batch "job-3d6ccb546fd16bb568c75fa2002f0c8d" not found
```

**Comment by h3poteto** [comment]
Could you please show me the `test.yaml` ?

**Comment by raine** [comment]
Sure!

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: default
spec:
  template:
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
      - name: xxx
        image: registry.gitlab.com/xxx/xxx:latest
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: secret
                key: database_url
          - name: PORT
            value: "3000"
      restartPolicy: Never
  backoffLimit: 4
```

**Comment by h3poteto** [comment]
I can reproduce this problem.

**Comment by h3poteto** [comment]
This error has occur when you specify wrong container name.
If you use following template file:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: test
        image: alpine:latest
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
```

you have to specify `test` as `--container` parameter. If you set other name, kube-job can't start the job, and says error.
